### ISSUE TITLE
DenyPermissionsEventParsing.PS1 does not kill active transfer

### ISSUE THREAD

**Issue by mol-tron** [SparkyzCodez/FSRM-Anti-ransomware#5]
When testing the the outputted DenyPermissionsEventParsing.PS1 script from $DenyPermissionsTriggeredScript, I noticed that it doesn't kill an active file copy session.  It seems the ACL on the file share is cached and only re-read when a new session is opened.  

Occasionally when testing a file copy of a group of 100 1mb-files to a Honeypot directory, it would allow me to copy all the files before my access was denied.

Adding this to the DenyPermissionsEventParsing.PS1 script successfully kills the file transfers more quickly and reliably.
`Get-SmbSession -ClientUserName $username | Close-SmbSession -Confirm:$false -force`

Referencing the development notes... disabling the user's account in Active Directory could take longer to propagate between DCs, especially in a larger AD environment.

**Comment by SparkyzCodez** [comment]
Hmmm, that's very interesting. My production environments aren't too big so I haven't encountered any issues that would come up and a very distributed network with lots of DCs.

Copying 100+ 1MB files to a honey pot before the lockout triggers is as I originally intended and that's been my experience too. I'm not saying this is right, but my viewpoint is that with honey pots I'm not too concerned with how many files that the black hat puts there. That's why this defaults to a passive file screen. The file I/O is allowed but the lockout is triggered. I've seen it take up to one minute for the lockout to occur. Personally I want them to dump some files so that I have some forensic evidence. Again, I'm not saying this is the right way, only that was my intent.

To both block AND lockout (same delay as above though) the honey pots should be set to "active" screens. The files can't be copied. FSRM detects the activity and calls the lockout script. Active screening slams the door shut before any file I/O can take place.

side note: I like the non-honey pot screens to be active for this reason.

Now that I've rambled a bit I have to say I really like your proposed change to the lockout script. I don't feel that this is a bug level issue, but I'm going to put some work into implementing your tweak. Thanks very much for bringing this up. That's a great contribution.

**Comment by mol-tron** [comment]
The more I think about it, I agree that's not really a bug and more of an enhancement to your script as it just insures the any existing connection is closed once the share permissions are changed.

I too like having forensic evidence to analyze, so on Honeypot folders I don't mind having "passive" screening types here.  There should only be dummy files in there anyhow.  In my environment once I make sure InDesign and some other programs don't falsely trigger the known ransomware files list, these screening types will be "active".

Overall, a fantastic script by the way.  Keep up the great work

**Comment by SparkyzCodez** [comment]
Created a new triggered script that has an option to disconnect all smb sessions when triggered.
